services:
  scale.io:
    container_name: api
    build:
      context: .
      dockerfile: API/Dockerfile
      target: dev
    volumes:
      - ./API:/app/API
      - ./Core:/app/Core
      - ./Infrastructure:/app/Infrastructure
      - ./Infrastructure/Persistence:/app/data
    command: dotnet watch run --project API/API.csproj --urls http://0.0.0.0:8080
    ports:
      - "5175:8080"
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - API_KEY=${API_KEY}
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}