services:
  scale.io:
    container_name: api
    build:
      context: .
      dockerfile: API/Dockerfile
      target: dev
    develop:
      watch:
        - path: ./API
          action: sync
          target: /app/API
        - path: ./Core
          action: sync
          target: /app/Core
        - path: ./Infrastructure
          action: sync
          target: /app/Infrastructure
    ports:
      - "5175:8080"
    volumes:
      - ./Infrastructure/Persistence:/app/data
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - API_KEY=${API_KEY}
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}