services:
    postgres:
        container_name: database
        image: postgres:16-alpine
        environment:
            - POSTGRES_DB=scaleio
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres -d scaleio" ]
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - postgres_data:/var/lib/postgresql/data

    scale.io:
        container_name: api
        build:
            context: .
            dockerfile: API/Dockerfile
            target: dev
        develop:
            watch:
                - path: ./API
                  action: sync
                  target: /app/API
                - path: ./Core
                  action: sync
                  target: /app/Core
                - path: ./Infrastructure
                  action: sync
                  target: /app/Infrastructure
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 40s
            start_interval: 5s
        ports:
            - "5175:8080"
        env_file: "API/.env"
        environment:
            - DATABASE_URL=Host=postgres;Port=5432;Database=scaleio;Username=postgres;Password=postgres
            - DOTNET_RUNNING_IN_CONTAINER=true
        depends_on:
            postgres:
                condition: service_healthy
        restart: on-failure

volumes:
    postgres_data:
