# fly.toml app configuration file generated for scale-io-api on 2025-10-24T17:04:16-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'scale-io-api'
primary_region = 'yyz'

[build]
  dockerfile = 'API/Dockerfile'
  ignorefile = '.dockerignore'
  build-target = 'final'

[env]
  ASPNETCORE_ENVIRONMENT = 'Production'
  ApplyMigrationsOnStartup = 'true'
  SeedDefaultUserOnStartup = 'true'
  Jwt__Audience = 'https://scale-io-api.fly.dev'
  Jwt__Issuer = 'https://scale-io-api.fly.dev'
  Jwt__TokenValidityMins = '60'
  Logging__LogLevel__Default = 'Information'
  Logging__LogLevel__Microsoft__AspNetCore = 'Warning'
  Sources__Global__FailureThreshold = '2'
  Sources__Global__CooldownSeconds = '120'
  Sources__Global__StaleWhileRevalidateSeconds = '1800'
  Sources__USDA__Enabled = 'true'
  Sources__USDA__TimeoutMs = '2200'
  Sources__GTINSearch__Enabled = 'true'
  Sources__GTINSearch__TimeoutMs = '4500'
  Sources__GTINSearchBarcode__Enabled = 'true'
  Sources__GTINSearchBarcode__TimeoutMs = '1800'
  Sources__OpenFoodFacts__Enabled = 'true'
  Sources__OpenFoodFacts__TimeoutMs = '1500'
  Sources__OpenFoodFactsBarcode__Enabled = 'true'
  Sources__OpenFoodFactsBarcode__TimeoutMs = '1200'
  Sources__OpenFoodFactsSearch__Enabled = 'false'
  Sources__OpenFoodFactsSearch__TimeoutMs = '1500'


[http_service]
  internal_port = 8080
  auto_stop_machines = 'stop'
  auto_start_machines = true
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
